from sage.all import *
import psycopg2
import sys


@parallel
def compute_data_at_level(N):
    conn = psycopg2.connect("dbname='modabvar' host='localhost'")
    c = conn.cursor()

    # Proceed only if no matching rows exist
    c.execute("""SELECT COUNT(*) FROM J0 WHERE level={}""".format(N))
    if c.fetchall()[0][0]:
        return 0

    J = J0(N)

    # Compute label
    the_label = "J0({})".format(N)

    # Compute level
    level = N

    # Compute dimension
    dimension = J.dimension()

    # Compute rational cusp subgroup
    # This is the group generated by differences of rational cusps
    Q_cusp_subgroup = J.rational_cusp_subgroup().order()

    # Compute rational cuspidal subgroup
    # This is the group generated by differences of cusps that are rational
    Q_cuspidal_subgroup = J.rational_cuspidal_subgroup().order()

    # Insert into table
    c.execute("""INSERT INTO J0 (
            the_label,
            level,
            dimension,
            Q_cusp_subgroup,
            Q_cuspidal_subgroup
            )
            VALUES (
            '{}',
            {},
            {},
            {},
            {}
            )
    """.format(
        the_label,
        level,
        dimension,
        Q_cusp_subgroup,
        Q_cuspidal_subgroup
        )
    )
    conn.commit()
    conn.close()


conn = psycopg2.connect("dbname='modabvar' host='localhost'")
c = conn.cursor()

c.execute("""CREATE TABLE IF NOT EXISTS J0
        (
        the_label TEXT,
        level INT PRIMARY KEY,
        dimension INT,
        Q_cusp_subgroup INT,
        Q_cuspidal_subgroup INT
        )
""")

conn.commit()
conn.close()

try:
    M = int(sys.argv[1])
except:
    M = 100

Ns = range(1, M+1)
list(compute_data_at_level(Ns))
